name: Study Complexity
favicon: null
layout_spectrum: 0.67728
typography_spectrum: 0.96695
title: Study Complexity
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#8a8b8d'
    - '#e79997'
    - '#50292a'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
